name: expense_tracker_app
description: "A pretty basic app to help me control my own expenses."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  currency_text_input_formatter: ^2.0.0
  path_provider: ^2.1.5
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  path: ^1.9.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.13
  drift_dev: ^2.28.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/app_icon_transparent.png"
  image_path_ios: "assets/icon/app_icon.png"
